INSERT INTO MERIT_LIST(MERIT_POS,EXAMINEE_ID) VALUES (1200,111111);

INSERT INTO CHOICE_LIST(MERIT_POS,PRIORITY_NO,UNI_SUB_ID) VALUES (1200,1,5);
INSERT INTO CHOICE_LIST(MERIT_POS,PRIORITY_NO,UNI_SUB_ID) VALUES (1200,2,6);
INSERT INTO CHOICE_LIST(MERIT_POS,PRIORITY_NO,UNI_SUB_ID) VALUES (1200,3,9);